import assert from 'node:assert/strict';
import {onRequestGet,onRequestHead} from '../../functions/api/v1/brilliancies/[[path]].js';
const id='br-'+'a'.repeat(64), snapshotId='snapshot-test';
const item={id,status:'published',white:{playerId:'fide-8602980'},black:{playerId:'fide-1'},themes:['queen-sacrifice'],event:{id:'event-test'}};
let shardFailure=false;
const assets=async input=>{
 const path=new URL(input).pathname;
 if(path.includes('/shards/')) return shardFailure ? new Response('',{status:503}) : Response.json({snapshotId,items:{[id]:item}});
 if(path.endsWith('items.json'))return Response.json([item,{...item,id:'br-'+'b'.repeat(64)}]);
 if(path.endsWith('manifest.json'))return Response.json({snapshotId,total:2});
 if(path.endsWith('.pgn'))return new Response('[Result "*"]\n\n1. e4 *');
 return new Response('',{status:404});
};
const ctx=(path='',query='',headers={})=>({request:new Request('https://chessdb.aigclabs.cc/api/v1/brilliancies'+query,{headers}),params:{path:path?[path]:[]},env:{ASSETS:{fetch:assets}}});
for(const q of ['?limit=0','?limit=101','?offset=-1','?offset=99999999999999999999','?cursor='+btoa(JSON.stringify({offset:0.5}))])assert.equal((await onRequestGet(ctx('',q))).status,400);
let r=await onRequestGet(ctx('','?limit=1'));const first=await r.json();assert.ok(first.nextCursor);
r=await onRequestGet(ctx('','?limit=1&theme=other&cursor='+encodeURIComponent(first.nextCursor)));assert.equal(r.status,400);
r=await onRequestGet(ctx('','?player=860'));assert.equal((await r.json()).total,0);
r=await onRequestGet(ctx('','?player=fide-8602980'));assert.equal((await r.json()).total,2);
r=await onRequestGet(ctx(id+'.json'));const etag=r.headers.get('etag');assert.ok(etag);
assert.equal((await onRequestGet(ctx(id+'.json','',{'if-none-match':etag}))).status,304);
assert.equal(await (await onRequestHead(ctx(id+'.json'))).text(),'');
assert.equal((await onRequestGet(ctx(id+'.pgn','?snapshot=old'))).status,409);
item.status='withdrawn';for(const ext of ['json','pgn'])assert.equal((await onRequestGet(ctx(id+'.'+ext))).status,410);
shardFailure=true;assert.equal((await onRequestGet(ctx(id+'.pgn'))).status,503);
r=await onRequestGet(ctx('','?theme='+encodeURIComponent('中文\r\n"')));assert.equal(r.status,200);
console.log('Brilliancies API: pagination, filtering, ETag, HEAD, withdrawal and fail-closed PGN passed');
