#!/usr/bin/env python3
"""Export a mimic profile (books + style + polyglot random table) as JS
for the browser test page.

  python3 export_web_profile.py --profile profiles/fide-8640980 --out webplay/profile.js
"""

from __future__ import annotations

import argparse
import json
import pathlib
import struct

import chess.polyglot


def read_book(path: pathlib.Path) -> list[dict]:
    entries = []
    if not path.exists():
        return entries
    data = path.read_bytes()
    for offset in range(0, len(data) - 15, 16):
        key, move, weight, _learn = struct.unpack_from(">QHHI", data, offset)
        entries.append({"k": f"{key:016x}", "m": move, "w": weight})
    return entries


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--profile", type=pathlib.Path, required=True)
    parser.add_argument("--out", type=pathlib.Path, required=True)
    args = parser.parse_args()

    style = json.loads((args.profile / "style.json").read_text(encoding="utf-8"))
    style.pop("gamesMeta", None)  # keep the page light
    payload = {
        "style": style,
        "bookWhite": read_book(args.profile / "white.bin"),
        "bookBlack": read_book(args.profile / "black.bin"),
    }
    random_hex = [f"{value:016x}" for value in chess.polyglot.POLYGLOT_RANDOM_ARRAY]

    js = (
        "// Generated by export_web_profile.py — do not edit.\n"
        f"window.MIMIC_PROFILE = {json.dumps(payload, ensure_ascii=False)};\n"
        f"window.POLYGLOT_RANDOM = {json.dumps(random_hex)};\n"
    )
    args.out.write_text(js, encoding="utf-8")
    print(f"wrote {args.out} ({args.out.stat().st_size} bytes, "
          f"{len(payload['bookWhite'])}+{len(payload['bookBlack'])} book entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
